comment:
  image:
    repository: yunusovtr/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: yunusovtr/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: yunusovtr/ui
    tag: latest
  service:
    externalPort: 9292

mongodb:
  usePassword: false
