---
apiVersion: v1
data:
  tls.crt: |
          LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVYzFFNkR1emcv
          ZEFLSGJBWGtmNk82bnpHZnMwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dERVdNQlFHQTFVRUF3d05O
          VEV1TWpVd0xqZzVMakkxTWpBZUZ3MHlNakExTVRReE1UTXpNamhhRncweQpNekExTVRReE1UTXpN
          amhhTUJneEZqQVVCZ05WQkFNTURUVXhMakkxTUM0NE9TNHlOVEl3Z2dFaU1BMEdDU3FHClNJYjNE
          UUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURyaElUQzlkWEZ3RWVlNS91RENvVzNIUUQrZS9jcHhK
          YzUKekpJWVEvcTFzbEMwVlV6QWU3bENKMFo4RDV6REM2ZkFnYWZYRkQ2WHBFeE1maHpTTm53MFVv
          WndkSTJ5Q1V2agp4eDJoZWFiNC9ncTA1RVd0UFQ5SE1SZ09pNm9tWVcyajNjMDg5VGZjaERjN0hy
          WCtRbkUzQWlwMXVmaURrbEZLCkVSeWJtaDB5ZERpdFRWcjYzaHFrWk5mbklMaUN0Uk9hc1p6UDQv
          Y3puUCtXNFBScmtnUEYzbnZDc0pBSXplSjQKREhMeEwrZ3RqcTJBWDB4SFp5NW5YTWZtdXM4M0NN
          d2lwLzRSRTlPQXNnUU1oWkl4TnJjYnN5ZjFiQ09ZeldpQwpUUDhzTEVNb3dyc0ttSXE2VDJEaEJa
          TXhrVWVVbk9sdEQyekt2VlVucnlqT0t3a3VjR0ROQWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JC
          UW5SYjdWTThOYVlUdFJrU2ZsRXltd0pTdlRrakFmQmdOVkhTTUVHREFXZ0JRblJiN1YKTThOYVlU
          dFJrU2ZsRXltd0pTdlRrakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dV
          QQpBNElCQVFDdzlFTnNMQ3RFbmdTelRpU3RIeVBTUXo1Vmg1c3J6enJoQmFtZ1dHck9MM3Zzc2Zl
          bjZFL0VJWnIwCk1keFBQTTZLSHZDejFTeUtLdHczK1dLZjVlVTNVMmZqTVBZVDNBb1JnSzRRWFRr
          Ykh5NjdtVWpuWHA5aDJtblUKdVFKaVlET3pseW1ndjFod0NrVElQS2F1V2lxSzFZNjQ1S1VrSkxz
          Z1BkeHUzck1qMXR4N1R4dnRhaWZ3Sy83SQpsbU1NZU5MZkxOSlhJQ2tMay9aV2J4QjdtUGwrajQ5
          cy8xei9nQXRocTNieUtPYk1HY0pvc3I5M0VTdGtabmlQCnFSVkM0SkdrNjk3MXYwckZlYTZWMTZO
          akxVbmJlTi9hWXRRcGVkbGtFdDhiVFc0Ym1McWtPbm5qVVhOMGdibDAKaDJsSFRKZTBMRXdndjIr
          cWFiOVROZi9NL1pMWgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
          LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
          QVNDQktjd2dnU2pBZ0VBQW9JQkFRRHJoSVRDOWRYRndFZWUKNS91RENvVzNIUUQrZS9jcHhKYzV6
          SklZUS9xMXNsQzBWVXpBZTdsQ0owWjhENXpEQzZmQWdhZlhGRDZYcEV4TQpmaHpTTm53MFVvWndk
          STJ5Q1V2anh4MmhlYWI0L2dxMDVFV3RQVDlITVJnT2k2b21ZVzJqM2MwODlUZmNoRGM3CkhyWCtR
          bkUzQWlwMXVmaURrbEZLRVJ5Ym1oMHlkRGl0VFZyNjNocWtaTmZuSUxpQ3RST2FzWnpQNC9jem5Q
          K1cKNFBScmtnUEYzbnZDc0pBSXplSjRESEx4TCtndGpxMkFYMHhIWnk1blhNZm11czgzQ013aXAv
          NFJFOU9Bc2dRTQpoWkl4TnJjYnN5ZjFiQ09ZeldpQ1RQOHNMRU1vd3JzS21JcTZUMkRoQlpNeGtV
          ZVVuT2x0RDJ6S3ZWVW5yeWpPCkt3a3VjR0ROQWdNQkFBRUNnZ0VBVGUrSlcxYXNpZ2JwN0d6Sjd3
          QXhaWG9FbFRJQ2hXRFh4am1xOHJxMElTSkQKMEprVmovQ2hTb0hpc2pVY1kvTGNiVGk2aU5MYkw2
          VWYxb1E1RjFzT1dPWWlOTjVzOFVoZ1E1emxja1RtZXlqZAo5Q1JCNW1VSkpvN1piaDdMakczYk1V
          bTVtLzF0b2R4aXhuNlFMUFpocnBsWjRhRkwyb1kxdmpQUmFyQmlEd3FDCkR6NEVBYnZWZ3Z1cTlO
          ZDg0bGZGZ2dDNlBQMFRqMFVEZGlSUGl0MUtMdEFIMDYyQ1NXeE9iMmljL253UlZsa0gKbUh5K1BJ
          ZHdVMFBWUXh4Y3dtRDNId2szNWMxQzU2Qit5alk0Y0JXL2RHQmlKZWNiVGFMWXM4RHBiZXBXaDFl
          SwozcFBydmZycGRyWVljYzg5TUdEU0RReTA2MkNQNS9pUmZBbTJUR2pOeFFLQmdRRDhxREgrUzNr
          UmRBc1hkRkRzCjg4SGl3UmEyWStER2xDRTNpUDB2VEM5T0N3a1l0L3o3TmZzZ0VDMmtaeFo5OEJX
          anNZZFVadzZLQUtrRDhnTTQKd3VNOFQ3VDhhd3F3a1dMNkptMmh4dm8wTUV1WFg5Ri9zNTU3R0s4
          WmdGclBvaHB4VkwwZU56eVQxVkU1NmxJYgovTlYrTUV4RS9GSTE5cFdqeER2QmhWMHF6d0tCZ1FE
          dW9rUyt1UTF1NktNbTBqdURQMGxwUnZzalE4R05NREtUCkJ3aTdwMHBoY2lQZHZUelhuUFFHaml5
          NzdFTmVucXBHVlpqNzF1SU96d2Jjam9nY3dSMHl6bHAxelg3Z1J2WjYKVTVRTndjTmJnT1Z0aTd1
          UFc5bXBNRHFTMUtEZkRpSnl2YUI0S2YyTVI2bnNkNkxucHQxaHMzVWVHaWszRGNhTgp1ejZ1KzJ1
          eG93S0JnRFBBZi8wR21KWHFueHIreUZUQTJVWUpKdzNWQjRXbGNlaGVOdjRwTE1kZm0wMWs0bnpT
          ClljMy9nbG5hZzlEb0RJYXJKbjB6WHRjRnE1a1RTWFdtOWNTMHp1MmxQMXRMYkdxdzFHUCt6ZUZD
          d3prT2Qyc2cKNzZWbk9QYVFSQW1qdXFiY0pLQzd6N3k0UlJzSDFDbkhjRE9ZMFFhUWFJYUZLOEdQ
          d0cyelU1SWhBb0dBV1NUaApEV1pQc0ZqVGFkTXJUREkrR0VmZDFTU2dqeitzQk9TaHpJZ0g3ek1X
          VnVVMGIwOUFrWnBXOTdTZ3poM3plZWJNCkNYZ1Nabm5NRkdSaVVHdUxuc2tiWGRwd1JSUDlTMkVo
          YzZvb2NteEtTSXZrZXY5UzVqTVFEbjNEd3MraTZyNFAKemhQUmxhL0h1SUJRcUx6YkFuNXBoOTg1
          K2tqNUhVVVBlNHFNaG9VQ2dZRUFqRklCMjFycnNSMTdDdWZMdU5zbgpnRmlVV1owUmJDVmdVY2tT
          NXZnYWxFZ2phUzk1ek5OZTdSbVVGeHlCZWRwbkpESGZCMC8rWHZKV0VTQjlzRzV1CklmSGJjLzZI
          dEpFZlQzazJ0dDd2WnFyY0RwY0dudTRTbTBQdTdCeTRJeE5URVF2amt3b3JKZjZ3Zmw3R21vb0kK
          MG5YVStORGt4aGJGWlloTGs2dkVJVDA9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: ui-ingress
  namespace: dev
type: kubernetes.io/tls
